#!/usr/bin/env bash
set -euo pipefail

if [ "$#" -eq 0 ]; then
  printf '%s\n' 'usage: with-dev-umask.sh <command> [args...]' >&2
  exit 64
fi

# Keep files generated by developer commands writable through the repository's
# shared codex-dev group even when the caller's login umask is restrictive.
umask 0002
exec "$@"
